version = "1.0"

[metadata]
difficulty = "medium"
category = "feature"
tags = [ "scala", "library", "cats",]

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 900.0
cpus = 2
memory_mb = 4096
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
