version = "1.0"

[metadata]
difficulty = "hard"
category = "feature"
tags = [ "scala", "backend", "kafka",]

[verifier]
timeout_sec = 1200.0

[agent]
timeout_sec = 1200.0

[environment]
build_timeout_sec = 1200.0
cpus = 1
memory_mb = 12288
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
