version = "1.0"

[metadata]
difficulty = "medium"
category = "bugfix"
tags = [ "java", "library", "kafka-streams",]

[verifier]
timeout_sec = 1200.0

[agent]
timeout_sec = 1200.0

[environment]
build_timeout_sec = 600.0
cpus = 4
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
