version = "1.0"

[metadata]
difficulty = "medium"
category = "feature"
tags = [ "java", "backend", "gradle",]

[verifier]
timeout_sec = 1200.0

[agent]
timeout_sec = 1200.0

[environment]
build_timeout_sec = 1200.0
cpus = 2
memory_mb = 4096
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
