version = "1.0"

[metadata]
difficulty = "medium"
category = "bugfix"
tags = [ "java", "backend", "kafka",]

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 3600.0

[environment]
build_timeout_sec = 1200.0
cpus = 2
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true

[verifier.env]

[solution.env]
